import type { NextPage } from 'next'
import { useRouter } from 'next/router';

import Head from 'next/head';
import Image from 'next/image';

import Button from '@mui/material/Button';

import styles from './home.module.css';

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>SVG MAP INTERACTIVE MAP</h1>
          <Button danger
                  type="default"
                  onClick={() => router.push('/about')}
          >
              About (COMING SOON)
          </Button>
          <Button danger
                  type="default"
                  onClick={() => router.push('/login')}
          >
              Login (COMING SOON)
          </Button>
          <Button danger
                  type="default"
                  onClick={() => router.push('/user')}
          >
              User (COMING SOON)
          </Button>
          <Button danger
                  type="default"
                  onClick={() => router.push('/plogg')}
          >
              List Ploggs (COMING SOON)
          </Button>
          <Button danger
                  type="default"
                  onClick={() => router.push('/plogg/insert')}
          >
              Add Plogg (FORM) (COMING SOON)
          </Button>
          <Button danger
                  type="default"
                  onClick={() => router.push('/plogg/1')}
          >
              Detail Plogg (COMING SOON)
          </Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://guebbit.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/svg/guebbit-logo.svg" alt="Guebbit Logo" width={50} height={50} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
